class CurrencyData {
  // Popular Currencies (Ranked 1-10)
  static const List<String> popularCodes = [
    'JPY', // Japan
    'VND', // Vietnam
    'THB', // Thailand
    'USD', // USA
    'CNY', // China
    'IDR', // Indonesia
    'PHP', // Philippines
    'SGD', // Singapore
    'TWD', // Taiwan
    'HKD', // Hong Kong
  ];

  /// Korean Currency Names (Restored for legacy support)
  static const Map<String, String> currencyNames = {
    'JPY': '엔',
    'VND': '동',
    'THB': '바트',
    'USD': '달러',
    'CNY': '위안',
    'IDR': '루피아',
    'PHP': '페소',
    'SGD': '달러',
    'TWD': '달러',
    'HKD': '달러',
    'EUR': '유로',
    'GBP': '파운드',
    'CHF': '프랑',
    'CAD': '달러',
    'AUD': '달러',
    'NZD': '달러',
    'MYR': '링깃',
    'INR': '루피',
    'TRY': '리라',
    'MXN': '페소',
    'BGN': '레프',
    'CZK': '코루나',
    'DKK': '크로네',
    'HUF': '포린트',
    'ILS': '셰켈',
    'ISK': '크로나',
    'NOK': '크로네',
    'PLN': '즈워티',
    'RON': '레우',
    'SEK': '크로나',
    'BRL': '헤알',
    'ZAR': '랜드',
    'KRW': '원',
    'RUB': '루블',
  };

  /// Typical Tip Percentages by Currency
  static const Map<String, int> defaultTips = {
    'KRW': 0,
    'JPY': 0,
    'CNY': 0,
    'HKD': 0,
    'TWD': 0,
    'THB': 0,
    'VND': 0,
    'IDR': 0,
    'PHP': 10,
    'SGD': 0,
    'MYR': 0,
    'INR': 10,
    'USD': 18,
    'CAD': 15,
    'MXN': 10,
    'EUR': 10,
    'GBP': 10,
    'CHF': 0,
    'TRY': 10,
    'BGN': 10,
    'CZK': 10,
    'DKK': 0,
    'HUF': 10,
    'ILS': 12,
    'ISK': 0,
    'NOK': 0,
    'PLN': 10,
    'RON': 10,
    'SEK': 0,
    'AUD': 0,
    'NZD': 0,
    'BRL': 10,
    'ZAR': 10,
  };

  static int getDefaultTip(String code) {
    return defaultTips[code] ?? 0;
  }

  /// Get country name by currency code.
  /// If multiple countries use the currency, returns a representative one
  /// logic: Find first entry in allCountries that matches the currency.
  static String getCountryName(String currencyCode) {
    try {
      final country = allCountries.firstWhere(
        (c) => c['currency'] == currencyCode,
      );
      return country['countryKR'] ?? currencyCode;
    } catch (_) {
      return currencyCode;
    }
  }

  /// Get flag code (ISO 3166-1 alpha-2) by country name (KR) or currency code.
  /// Get flag emoji by country name (KR) or currency code.
  static String getFlag(String query) {
    try {
      String? flagCode;

      // 1. Try match by countryKR
      var country = allCountries.firstWhere(
        (c) => c['countryKR'] == query,
        orElse: () => {},
      );
      if (country.isNotEmpty) flagCode = country['flag'];

      // 2. Try match by currency (representative)
      if (flagCode == null) {
        country = allCountries.firstWhere(
          (c) => c['currency'] == query,
          orElse: () => {},
        );
        if (country.isNotEmpty) flagCode = country['flag'];
      }

      return countryCodeToEmoji(flagCode ?? 'UN');
    } catch (_) {
      return countryCodeToEmoji('UN');
    }
  }

  static String countryCodeToEmoji(String countryCode) {
    if (countryCode.length != 2) return '';
    final int firstLetter =
        countryCode.toUpperCase().codeUnitAt(0) - 0x41 + 0x1F1E6;
    final int secondLetter =
        countryCode.toUpperCase().codeUnitAt(1) - 0x41 + 0x1F1E6;
    return String.fromCharCode(firstLetter) + String.fromCharCode(secondLetter);
  }

  /// Get language code for TTS (e.g., 'ko', 'en-US')
  static String getLanguageCode(String countryKR) {
    try {
      final country = allCountries.firstWhere(
        (c) => c['countryKR'] == countryKR,
        orElse: () => {},
      );
      if (country.isNotEmpty && country['language'] != null) {
        return country['language']!.toLowerCase();
      }
      return 'en';
    } catch (_) {
      return 'en';
    }
  }

  // Standardized Data Table (Generated from CSV)
  // Fields: countryKR, countryEN, currency, language, flag
  static const List<Map<String, String>> allCountries = [
    {
      'countryKR': '아랍에미리트',
      'countryEN': 'United Arab Emirates',
      'currency': 'AED',
      'language': 'AR',
      'flag': 'AE',
    },
    {
      'countryKR': '아프가니스탄',
      'countryEN': 'Afghanistan',
      'currency': 'AFN',
      'language': 'FA',
      'flag': 'AF',
    },
    {
      'countryKR': '알바니아',
      'countryEN': 'Albania',
      'currency': 'ALL',
      'language': 'SQ',
      'flag': 'AL',
    },
    {
      'countryKR': '아르메니아',
      'countryEN': 'Armenia',
      'currency': 'AMD',
      'language': 'HY',
      'flag': 'AM',
    },
    {
      'countryKR': '앙골라',
      'countryEN': 'Angola',
      'currency': 'AOA',
      'language': 'PT',
      'flag': 'AO',
    },
    {
      'countryKR': '아르헨티나',
      'countryEN': 'Argentina',
      'currency': 'ARS',
      'language': 'ES',
      'flag': 'AR',
    },
    {
      'countryKR': '오스트레일리아',
      'countryEN': 'Australia',
      'currency': 'AUD',
      'language': 'EN',
      'flag': 'AU',
    },
    {
      'countryKR': '코코스 제도',
      'countryEN': 'Cocos (Keeling) Islands',
      'currency': 'AUD',
      'language': 'MS',
      'flag': 'CC',
    },
    {
      'countryKR': '크리스마스섬',
      'countryEN': 'Christmas Island',
      'currency': 'AUD',
      'language': 'EN',
      'flag': 'CX',
    },
    {
      'countryKR': '키리바시',
      'countryEN': 'Kiribati',
      'currency': 'AUD',
      'language': 'EN',
      'flag': 'KI',
    },
    {
      'countryKR': '노퍽섬',
      'countryEN': 'Norfolk Island',
      'currency': 'AUD',
      'language': 'EN',
      'flag': 'NF',
    },
    {
      'countryKR': '나우루',
      'countryEN': 'Nauru',
      'currency': 'AUD',
      'language': 'EN',
      'flag': 'NR',
    },
    {
      'countryKR': '투발루',
      'countryEN': 'Tuvalu',
      'currency': 'AUD',
      'language': 'TVL',
      'flag': 'TV',
    },
    {
      'countryKR': '아루바',
      'countryEN': 'Aruba',
      'currency': 'AWG',
      'language': 'NL',
      'flag': 'AW',
    },
    {
      'countryKR': '아제르바이잔',
      'countryEN': 'Azerbaijan',
      'currency': 'AZN',
      'language': 'AZ',
      'flag': 'AZ',
    },
    {
      'countryKR': '보스니아 헤르체고비나',
      'countryEN': 'Bosnia and Herzegovina',
      'currency': 'BAM',
      'language': 'BS',
      'flag': 'BA',
    },
    {
      'countryKR': '바베이도스',
      'countryEN': 'Barbados',
      'currency': 'BBD',
      'language': 'EN',
      'flag': 'BB',
    },
    {
      'countryKR': '방글라데시',
      'countryEN': 'Bangladesh',
      'currency': 'BDT',
      'language': 'BN',
      'flag': 'BD',
    },
    {
      'countryKR': '불가리아',
      'countryEN': 'Bulgaria',
      'currency': 'BGN',
      'language': 'BG',
      'flag': 'BG',
    },
    {
      'countryKR': '바레인',
      'countryEN': 'Bahrain',
      'currency': 'BHD',
      'language': 'AR',
      'flag': 'BH',
    },
    {
      'countryKR': '부룬디',
      'countryEN': 'Burundi',
      'currency': 'BIF',
      'language': 'RN',
      'flag': 'BI',
    },
    {
      'countryKR': '버뮤다',
      'countryEN': 'Bermuda',
      'currency': 'BMD',
      'language': 'EN',
      'flag': 'BM',
    },
    {
      'countryKR': '브루나이',
      'countryEN': 'Brunei Darussalam',
      'currency': 'BND',
      'language': 'MS',
      'flag': 'BN',
    },
    {
      'countryKR': '부베섬',
      'countryEN': 'Bouvet Island',
      'currency': 'NOK',
      'language': 'NB',
      'flag': 'BV',
    },
    {
      'countryKR': '볼리비아',
      'countryEN': 'Bolivia, Plurinational State of',
      'currency': 'BOB',
      'language': 'ES',
      'flag': 'BO',
    },
    {
      'countryKR': '브라질',
      'countryEN': 'Brazil',
      'currency': 'BRL',
      'language': 'PT',
      'flag': 'BR',
    },
    {
      'countryKR': '바하마',
      'countryEN': 'Bahamas',
      'currency': 'BSD',
      'language': 'EN',
      'flag': 'BS',
    },
    {
      'countryKR': '부탄',
      'countryEN': 'Bhutan',
      'currency': 'BTN',
      'language': 'DZ',
      'flag': 'BT',
    },
    {
      'countryKR': '보츠와나',
      'countryEN': 'Botswana',
      'currency': 'BWP',
      'language': 'EN',
      'flag': 'BW',
    },
    {
      'countryKR': '벨라루스',
      'countryEN': 'Belarus',
      'currency': 'BYN',
      'language': 'BE',
      'flag': 'BY',
    },
    {
      'countryKR': '벨리즈',
      'countryEN': 'Belize',
      'currency': 'BZD',
      'language': 'EN',
      'flag': 'BZ',
    },
    {
      'countryKR': '캐나다',
      'countryEN': 'Canada',
      'currency': 'CAD',
      'language': 'EN',
      'flag': 'CA',
    },
    {
      'countryKR': '콩고-킨샤사',
      'countryEN': 'Congo, The Democratic Republic of the',
      'currency': 'CDF',
      'language': 'SW',
      'flag': 'CD',
    },
    {
      'countryKR': '스위스',
      'countryEN': 'Switzerland',
      'currency': 'CHF',
      'language': 'DE',
      'flag': 'CH',
    },
    {
      'countryKR': '리히텐슈타인',
      'countryEN': 'Liechtenstein',
      'currency': 'CHF',
      'language': 'DE',
      'flag': 'LI',
    },
    {
      'countryKR': '칠레',
      'countryEN': 'Chile',
      'currency': 'CLP',
      'language': 'ES',
      'flag': 'CL',
    },
    {
      'countryKR': '중국',
      'countryEN': 'China',
      'currency': 'CNY',
      'language': 'ZH',
      'flag': 'CN',
    },
    {
      'countryKR': '콜롬비아',
      'countryEN': 'Colombia',
      'currency': 'COP',
      'language': 'ES',
      'flag': 'CO',
    },
    {
      'countryKR': '코스타리카',
      'countryEN': 'Costa Rica',
      'currency': 'CRC',
      'language': 'ES',
      'flag': 'CR',
    },
    {
      'countryKR': '쿠바',
      'countryEN': 'Cuba',
      'currency': 'CUP',
      'language': 'ES',
      'flag': 'CU',
    },
    {
      'countryKR': '카보베르데',
      'countryEN': 'Cabo Verde',
      'currency': 'CVE',
      'language': 'PT',
      'flag': 'CV',
    },
    {
      'countryKR': '체코',
      'countryEN': 'Czechia',
      'currency': 'CZK',
      'language': 'CS',
      'flag': 'CZ',
    },
    {
      'countryKR': '지부티',
      'countryEN': 'Djibouti',
      'currency': 'DJF',
      'language': 'AA',
      'flag': 'DJ',
    },
    {
      'countryKR': '덴마크',
      'countryEN': 'Denmark',
      'currency': 'DKK',
      'language': 'DA',
      'flag': 'DK',
    },
    {
      'countryKR': '페로 제도',
      'countryEN': 'Faroe Islands',
      'currency': 'DKK',
      'language': 'FO',
      'flag': 'FO',
    },
    {
      'countryKR': '그린란드',
      'countryEN': 'Greenland',
      'currency': 'DKK',
      'language': 'KL',
      'flag': 'GL',
    },
    {
      'countryKR': '도미니카 공화국',
      'countryEN': 'Dominican Republic',
      'currency': 'DOP',
      'language': 'ES',
      'flag': 'DO',
    },
    {
      'countryKR': '알제리',
      'countryEN': 'Algeria',
      'currency': 'DZD',
      'language': 'AR',
      'flag': 'DZ',
    },
    {
      'countryKR': '이집트',
      'countryEN': 'Egypt',
      'currency': 'EGP',
      'language': 'AR',
      'flag': 'EG',
    },
    {
      'countryKR': '에리트리아',
      'countryEN': 'Eritrea',
      'currency': 'ERN',
      'language': 'TI',
      'flag': 'ER',
    },
    {
      'countryKR': '에티오피아',
      'countryEN': 'Ethiopia',
      'currency': 'ETB',
      'language': 'AM',
      'flag': 'ET',
    },
    {
      'countryKR': '안도라',
      'countryEN': 'Andorra',
      'currency': 'EUR',
      'language': 'CA',
      'flag': 'AD',
    },
    {
      'countryKR': '오스트리아',
      'countryEN': 'Austria',
      'currency': 'EUR',
      'language': 'DE',
      'flag': 'AT',
    },
    {
      'countryKR': '올란드 제도',
      'countryEN': 'Åland Islands',
      'currency': 'EUR',
      'language': 'SV',
      'flag': 'AX',
    },
    {
      'countryKR': '벨기에',
      'countryEN': 'Belgium',
      'currency': 'EUR',
      'language': 'NL',
      'flag': 'BE',
    },
    {
      'countryKR': '생바르텔레미',
      'countryEN': 'Saint Barthélemy',
      'currency': 'EUR',
      'language': 'FR',
      'flag': 'BL',
    },
    {
      'countryKR': '키프로스',
      'countryEN': 'Cyprus',
      'currency': 'EUR',
      'language': 'EL',
      'flag': 'CY',
    },
    {
      'countryKR': '독일',
      'countryEN': 'Germany',
      'currency': 'EUR',
      'language': 'DE',
      'flag': 'DE',
    },
    {
      'countryKR': '에스토니아',
      'countryEN': 'Estonia',
      'currency': 'EUR',
      'language': 'ET',
      'flag': 'EE',
    },
    {
      'countryKR': '스페인',
      'countryEN': 'Spain',
      'currency': 'EUR',
      'language': 'ES',
      'flag': 'ES',
    },
    {
      'countryKR': '핀란드',
      'countryEN': 'Finland',
      'currency': 'EUR',
      'language': 'FI',
      'flag': 'FI',
    },
    {
      'countryKR': '프랑스',
      'countryEN': 'France',
      'currency': 'EUR',
      'language': 'FR',
      'flag': 'FR',
    },
    {
      'countryKR': '프랑스령 기아나',
      'countryEN': 'French Guiana',
      'currency': 'EUR',
      'language': 'FR',
      'flag': 'GF',
    },
    {
      'countryKR': '과들루프',
      'countryEN': 'Guadeloupe',
      'currency': 'EUR',
      'language': 'FR',
      'flag': 'GP',
    },
    {
      'countryKR': '그리스',
      'countryEN': 'Greece',
      'currency': 'EUR',
      'language': 'EL',
      'flag': 'GR',
    },
    {
      'countryKR': '크로아티아',
      'countryEN': 'Croatia',
      'currency': 'EUR',
      'language': 'HR',
      'flag': 'HR',
    },
    {
      'countryKR': '아일랜드',
      'countryEN': 'Ireland',
      'currency': 'EUR',
      'language': 'EN',
      'flag': 'IE',
    },
    {
      'countryKR': '이탈리아',
      'countryEN': 'Italy',
      'currency': 'EUR',
      'language': 'IT',
      'flag': 'IT',
    },
    {
      'countryKR': '리투아니아',
      'countryEN': 'Lithuania',
      'currency': 'EUR',
      'language': 'LT',
      'flag': 'LT',
    },
    {
      'countryKR': '룩셈부르크',
      'countryEN': 'Luxembourg',
      'currency': 'EUR',
      'language': 'FR',
      'flag': 'LU',
    },
    {
      'countryKR': '라트비아',
      'countryEN': 'Latvia',
      'currency': 'EUR',
      'language': 'LV',
      'flag': 'LV',
    },
    {
      'countryKR': '모나코',
      'countryEN': 'Monaco',
      'currency': 'EUR',
      'language': 'FR',
      'flag': 'MC',
    },
    {
      'countryKR': '몬테네그로',
      'countryEN': 'Montenegro',
      'currency': 'EUR',
      'language': 'SR',
      'flag': 'ME',
    },
    {
      'countryKR': '생마르탱',
      'countryEN': 'Saint Martin (French part)',
      'currency': 'EUR',
      'language': 'FR',
      'flag': 'MF',
    },
    {
      'countryKR': '마르티니크',
      'countryEN': 'Martinique',
      'currency': 'EUR',
      'language': 'FR',
      'flag': 'MQ',
    },
    {
      'countryKR': '몰타',
      'countryEN': 'Malta',
      'currency': 'EUR',
      'language': 'MT',
      'flag': 'MT',
    },
    {
      'countryKR': '네덜란드',
      'countryEN': 'Netherlands',
      'currency': 'EUR',
      'language': 'NL',
      'flag': 'NL',
    },
    {
      'countryKR': '생피에르 미클롱',
      'countryEN': 'Saint Pierre and Miquelon',
      'currency': 'EUR',
      'language': 'FR',
      'flag': 'PM',
    },
    {
      'countryKR': '포르투갈',
      'countryEN': 'Portugal',
      'currency': 'EUR',
      'language': 'PT',
      'flag': 'PT',
    },
    {
      'countryKR': '레위니옹',
      'countryEN': 'Réunion',
      'currency': 'EUR',
      'language': 'FR',
      'flag': 'RE',
    },
    {
      'countryKR': '슬로베니아',
      'countryEN': 'Slovenia',
      'currency': 'EUR',
      'language': 'SL',
      'flag': 'SI',
    },
    {
      'countryKR': '슬로바키아',
      'countryEN': 'Slovakia',
      'currency': 'EUR',
      'language': 'SK',
      'flag': 'SK',
    },
    {
      'countryKR': '산마리노',
      'countryEN': 'San Marino',
      'currency': 'EUR',
      'language': 'IT',
      'flag': 'SM',
    },
    {
      'countryKR': '바티칸 시국',
      'countryEN': 'Holy See (Vatican City State)',
      'currency': 'EUR',
      'language': 'IT',
      'flag': 'VA',
    },
    {
      'countryKR': '마요트',
      'countryEN': 'Mayotte',
      'currency': 'EUR',
      'language': 'FR',
      'flag': 'YT',
    },
    {
      'countryKR': '피지',
      'countryEN': 'Fiji',
      'currency': 'FJD',
      'language': 'EN',
      'flag': 'FJ',
    },
    {
      'countryKR': '포클랜드 제도',
      'countryEN': 'Falkland Islands (Malvinas)',
      'currency': 'FKP',
      'language': 'EN',
      'flag': 'FK',
    },
    {
      'countryKR': '영국',
      'countryEN': 'United Kingdom',
      'currency': 'GBP',
      'language': 'EN',
      'flag': 'GB',
    },
    {
      'countryKR': '건지',
      'countryEN': 'Guernsey',
      'currency': 'GBP',
      'language': 'EN',
      'flag': 'GG',
    },
    {
      'countryKR': '맨섬',
      'countryEN': 'Isle of Man',
      'currency': 'GBP',
      'language': 'EN',
      'flag': 'IM',
    },
    {
      'countryKR': '저지',
      'countryEN': 'Jersey',
      'currency': 'GBP',
      'language': 'EN',
      'flag': 'JE',
    },
    {
      'countryKR': '조지아',
      'countryEN': 'Georgia',
      'currency': 'GEL',
      'language': 'KA',
      'flag': 'GE',
    },
    {
      'countryKR': '가나',
      'countryEN': 'Ghana',
      'currency': 'GHS',
      'language': 'AK',
      'flag': 'GH',
    },
    {
      'countryKR': '지브롤터',
      'countryEN': 'Gibraltar',
      'currency': 'GIP',
      'language': 'EN',
      'flag': 'GI',
    },
    {
      'countryKR': '감비아',
      'countryEN': 'Gambia',
      'currency': 'GMD',
      'language': 'EN',
      'flag': 'GM',
    },
    {
      'countryKR': '기니',
      'countryEN': 'Guinea',
      'currency': 'GNF',
      'language': 'FR',
      'flag': 'GN',
    },
    {
      'countryKR': '과테말라',
      'countryEN': 'Guatemala',
      'currency': 'GTQ',
      'language': 'ES',
      'flag': 'GT',
    },
    {
      'countryKR': '가이아나',
      'countryEN': 'Guyana',
      'currency': 'GYD',
      'language': 'EN',
      'flag': 'GY',
    },
    {
      'countryKR': '홍콩(중국 특별행정구)',
      'countryEN': 'Hong Kong',
      'currency': 'HKD',
      'language': 'ZH',
      'flag': 'HK',
    },
    {
      'countryKR': '온두라스',
      'countryEN': 'Honduras',
      'currency': 'HNL',
      'language': 'ES',
      'flag': 'HN',
    },
    {
      'countryKR': '아이티',
      'countryEN': 'Haiti',
      'currency': 'HTG',
      'language': 'HT',
      'flag': 'HT',
    },
    {
      'countryKR': '헝가리',
      'countryEN': 'Hungary',
      'currency': 'HUF',
      'language': 'HU',
      'flag': 'HU',
    },
    {
      'countryKR': '인도네시아',
      'countryEN': 'Indonesia',
      'currency': 'IDR',
      'language': 'ID',
      'flag': 'ID',
    },
    {
      'countryKR': '이스라엘',
      'countryEN': 'Israel',
      'currency': 'ILS',
      'language': 'HE',
      'flag': 'IL',
    },
    {
      'countryKR': '팔레스타인 지구',
      'countryEN': 'Palestine, State of',
      'currency': 'ILS',
      'language': 'AR',
      'flag': 'PS',
    },
    {
      'countryKR': '부탄',
      'countryEN': 'Bhutan',
      'currency': 'INR',
      'language': 'DZ',
      'flag': 'BT',
    },
    {
      'countryKR': '인도',
      'countryEN': 'India',
      'currency': 'INR',
      'language': 'HI',
      'flag': 'IN',
    },
    {
      'countryKR': '이라크',
      'countryEN': 'Iraq',
      'currency': 'IQD',
      'language': 'AR',
      'flag': 'IQ',
    },
    {
      'countryKR': '이란',
      'countryEN': 'Iran, Islamic Republic of',
      'currency': 'IRR',
      'language': 'FA',
      'flag': 'IR',
    },
    {
      'countryKR': '아이슬란드',
      'countryEN': 'Iceland',
      'currency': 'ISK',
      'language': 'IS',
      'flag': 'IS',
    },
    {
      'countryKR': '자메이카',
      'countryEN': 'Jamaica',
      'currency': 'JMD',
      'language': 'EN',
      'flag': 'JM',
    },
    {
      'countryKR': '요르단',
      'countryEN': 'Jordan',
      'currency': 'JOD',
      'language': 'AR',
      'flag': 'JO',
    },
    {
      'countryKR': '일본',
      'countryEN': 'Japan',
      'currency': 'JPY',
      'language': 'JA',
      'flag': 'JP',
    },
    {
      'countryKR': '케냐',
      'countryEN': 'Kenya',
      'currency': 'KES',
      'language': 'SW',
      'flag': 'KE',
    },
    {
      'countryKR': '키르기스스탄',
      'countryEN': 'Kyrgyzstan',
      'currency': 'KGS',
      'language': 'KY',
      'flag': 'KG',
    },
    {
      'countryKR': '캄보디아',
      'countryEN': 'Cambodia',
      'currency': 'KHR',
      'language': 'KM',
      'flag': 'KH',
    },
    {
      'countryKR': '코모로',
      'countryEN': 'Comoros',
      'currency': 'KMF',
      'language': 'AR',
      'flag': 'KM',
    },
    {
      'countryKR': '북한',
      'countryEN': 'Korea, Democratic People\'s Republic of',
      'currency': 'KPW',
      'language': 'KO',
      'flag': 'KP',
    },
    {
      'countryKR': '대한민국',
      'countryEN': 'Korea, Republic of',
      'currency': 'KRW',
      'language': 'KO',
      'flag': 'KR',
    },
    {
      'countryKR': '쿠웨이트',
      'countryEN': 'Kuwait',
      'currency': 'KWD',
      'language': 'AR',
      'flag': 'KW',
    },
    {
      'countryKR': '케이맨 제도',
      'countryEN': 'Cayman Islands',
      'currency': 'KYD',
      'language': 'EN',
      'flag': 'KY',
    },
    {
      'countryKR': '카자흐스탄',
      'countryEN': 'Kazakhstan',
      'currency': 'KZT',
      'language': 'RU',
      'flag': 'KZ',
    },
    {
      'countryKR': '라오스',
      'countryEN': 'Lao People\'s Democratic Republic',
      'currency': 'LAK',
      'language': 'LO',
      'flag': 'LA',
    },
    {
      'countryKR': '레바논',
      'countryEN': 'Lebanon',
      'currency': 'LBP',
      'language': 'AR',
      'flag': 'LB',
    },
    {
      'countryKR': '스리랑카',
      'countryEN': 'Sri Lanka',
      'currency': 'LKR',
      'language': 'SI',
      'flag': 'LK',
    },
    {
      'countryKR': '라이베리아',
      'countryEN': 'Liberia',
      'currency': 'LRD',
      'language': 'EN',
      'flag': 'LR',
    },
    {
      'countryKR': '레소토',
      'countryEN': 'Lesotho',
      'currency': 'LSL',
      'language': 'ST',
      'flag': 'LS',
    },
    {
      'countryKR': '리비아',
      'countryEN': 'Libya',
      'currency': 'LYD',
      'language': 'AR',
      'flag': 'LY',
    },
    {
      'countryKR': '서사하라',
      'countryEN': 'Western Sahara',
      'currency': 'MAD',
      'language': 'AR',
      'flag': 'EH',
    },
    {
      'countryKR': '모로코',
      'countryEN': 'Morocco',
      'currency': 'MAD',
      'language': 'AR',
      'flag': 'MA',
    },
    {
      'countryKR': '몰도바',
      'countryEN': 'Moldova, Republic of',
      'currency': 'MDL',
      'language': 'RO',
      'flag': 'MD',
    },
    {
      'countryKR': '마다가스카르',
      'countryEN': 'Madagascar',
      'currency': 'MGA',
      'language': 'MG',
      'flag': 'MG',
    },
    {
      'countryKR': '북마케도니아',
      'countryEN': 'North Macedonia',
      'currency': 'MKD',
      'language': 'MK',
      'flag': 'MK',
    },
    {
      'countryKR': '미얀마',
      'countryEN': 'Myanmar',
      'currency': 'MMK',
      'language': 'MY',
      'flag': 'MM',
    },
    {
      'countryKR': '몽골',
      'countryEN': 'Mongolia',
      'currency': 'MNT',
      'language': 'MN',
      'flag': 'MN',
    },
    {
      'countryKR': '마카오(중국 특별행정구)',
      'countryEN': 'Macao',
      'currency': 'MOP',
      'language': 'ZH',
      'flag': 'MO',
    },
    {
      'countryKR': '모리타니',
      'countryEN': 'Mauritania',
      'currency': 'MRU',
      'language': 'AR',
      'flag': 'MR',
    },
    {
      'countryKR': '모리셔스',
      'countryEN': 'Mauritius',
      'currency': 'MUR',
      'language': 'MFE',
      'flag': 'MU',
    },
    {
      'countryKR': '몰디브',
      'countryEN': 'Maldives',
      'currency': 'MVR',
      'language': 'DV',
      'flag': 'MV',
    },
    {
      'countryKR': '말라위',
      'countryEN': 'Malawi',
      'currency': 'MWK',
      'language': 'EN',
      'flag': 'MW',
    },
    {
      'countryKR': '멕시코',
      'countryEN': 'Mexico',
      'currency': 'MXN',
      'language': 'ES',
      'flag': 'MX',
    },
    {
      'countryKR': '말레이시아',
      'countryEN': 'Malaysia',
      'currency': 'MYR',
      'language': 'MS',
      'flag': 'MY',
    },
    {
      'countryKR': '모잠비크',
      'countryEN': 'Mozambique',
      'currency': 'MZN',
      'language': 'PT',
      'flag': 'MZ',
    },
    {
      'countryKR': '나미비아',
      'countryEN': 'Namibia',
      'currency': 'NAD',
      'language': 'AF',
      'flag': 'NA',
    },
    {
      'countryKR': '나이지리아',
      'countryEN': 'Nigeria',
      'currency': 'NGN',
      'language': 'EN',
      'flag': 'NG',
    },
    {
      'countryKR': '니카라과',
      'countryEN': 'Nicaragua',
      'currency': 'NIO',
      'language': 'ES',
      'flag': 'NI',
    },
    {
      'countryKR': '노르웨이',
      'countryEN': 'Norway',
      'currency': 'NOK',
      'language': 'NB',
      'flag': 'NO',
    },
    {
      'countryKR': '스발바르제도-얀마웬섬',
      'countryEN': 'Svalbard and Jan Mayen',
      'currency': 'NOK',
      'language': 'NB',
      'flag': 'SJ',
    },
    {
      'countryKR': '네팔',
      'countryEN': 'Nepal',
      'currency': 'NPR',
      'language': 'NE',
      'flag': 'NP',
    },
    {
      'countryKR': '쿡 제도',
      'countryEN': 'Cook Islands',
      'currency': 'NZD',
      'language': 'EN',
      'flag': 'CK',
    },
    {
      'countryKR': '니우에',
      'countryEN': 'Niue',
      'currency': 'NZD',
      'language': 'EN',
      'flag': 'NU',
    },
    {
      'countryKR': '뉴질랜드',
      'countryEN': 'New Zealand',
      'currency': 'NZD',
      'language': 'EN',
      'flag': 'NZ',
    },
    {
      'countryKR': '핏케언 제도',
      'countryEN': 'Pitcairn',
      'currency': 'NZD',
      'language': 'EN',
      'flag': 'PN',
    },
    {
      'countryKR': '토켈라우',
      'countryEN': 'Tokelau',
      'currency': 'NZD',
      'language': 'TKL',
      'flag': 'TK',
    },
    {
      'countryKR': '오만',
      'countryEN': 'Oman',
      'currency': 'OMR',
      'language': 'AR',
      'flag': 'OM',
    },
    {
      'countryKR': '파나마',
      'countryEN': 'Panama',
      'currency': 'PAB',
      'language': 'ES',
      'flag': 'PA',
    },
    {
      'countryKR': '페루',
      'countryEN': 'Peru',
      'currency': 'PEN',
      'language': 'ES',
      'flag': 'PE',
    },
    {
      'countryKR': '파푸아뉴기니',
      'countryEN': 'Papua New Guinea',
      'currency': 'PGK',
      'language': 'TPI',
      'flag': 'PG',
    },
    {
      'countryKR': '필리핀',
      'countryEN': 'Philippines',
      'currency': 'PHP',
      'language': 'FIL',
      'flag': 'PH',
    },
    {
      'countryKR': '파키스탄',
      'countryEN': 'Pakistan',
      'currency': 'PKR',
      'language': 'UR',
      'flag': 'PK',
    },
    {
      'countryKR': '폴란드',
      'countryEN': 'Poland',
      'currency': 'PLN',
      'language': 'PL',
      'flag': 'PL',
    },
    {
      'countryKR': '파라과이',
      'countryEN': 'Paraguay',
      'currency': 'PYG',
      'language': 'GN',
      'flag': 'PY',
    },
    {
      'countryKR': '카타르',
      'countryEN': 'Qatar',
      'currency': 'QAR',
      'language': 'AR',
      'flag': 'QA',
    },
    {
      'countryKR': '루마니아',
      'countryEN': 'Romania',
      'currency': 'RON',
      'language': 'RO',
      'flag': 'RO',
    },
    {
      'countryKR': '세르비아',
      'countryEN': 'Serbia',
      'currency': 'RSD',
      'language': 'SR',
      'flag': 'RS',
    },
    {
      'countryKR': '러시아',
      'countryEN': 'Russian Federation',
      'currency': 'RUB',
      'language': 'RU',
      'flag': 'RU',
    },
    {
      'countryKR': '르완다',
      'countryEN': 'Rwanda',
      'currency': 'RWF',
      'language': 'RW',
      'flag': 'RW',
    },
    {
      'countryKR': '사우디아라비아',
      'countryEN': 'Saudi Arabia',
      'currency': 'SAR',
      'language': 'AR',
      'flag': 'SA',
    },
    {
      'countryKR': '솔로몬 제도',
      'countryEN': 'Solomon Islands',
      'currency': 'SBD',
      'language': 'EN',
      'flag': 'SB',
    },
    {
      'countryKR': '세이셸',
      'countryEN': 'Seychelles',
      'currency': 'SCR',
      'language': 'FR',
      'flag': 'SC',
    },
    {
      'countryKR': '수단',
      'countryEN': 'Sudan',
      'currency': 'SDG',
      'language': 'AR',
      'flag': 'SD',
    },
    {
      'countryKR': '스웨덴',
      'countryEN': 'Sweden',
      'currency': 'SEK',
      'language': 'SV',
      'flag': 'SE',
    },
    {
      'countryKR': '싱가포르',
      'countryEN': 'Singapore',
      'currency': 'SGD',
      'language': 'EN',
      'flag': 'SG',
    },
    {
      'countryKR': '세인트헬레나',
      'countryEN': 'Saint Helena, Ascension and Tristan da Cunha',
      'currency': 'SHP',
      'language': 'EN',
      'flag': 'SH',
    },
    {
      'countryKR': '시에라리온',
      'countryEN': 'Sierra Leone',
      'currency': 'SLE',
      'language': 'KRI',
      'flag': 'SL',
    },
    {
      'countryKR': '소말리아',
      'countryEN': 'Somalia',
      'currency': 'SOS',
      'language': 'SO',
      'flag': 'SO',
    },
    {
      'countryKR': '수리남',
      'countryEN': 'Suriname',
      'currency': 'SRD',
      'language': 'NL',
      'flag': 'SR',
    },
    {
      'countryKR': '남수단',
      'countryEN': 'South Sudan',
      'currency': 'SSP',
      'language': 'AR',
      'flag': 'SS',
    },
    {
      'countryKR': '상투메 프린시페',
      'countryEN': 'Sao Tome and Principe',
      'currency': 'STN',
      'language': 'PT',
      'flag': 'ST',
    },
    {
      'countryKR': '시리아',
      'countryEN': 'Syrian Arab Republic',
      'currency': 'SYP',
      'language': 'AR',
      'flag': 'SY',
    },
    {
      'countryKR': '에스와티니',
      'countryEN': 'Eswatini',
      'currency': 'SZL',
      'language': 'EN',
      'flag': 'SZ',
    },
    {
      'countryKR': '태국',
      'countryEN': 'Thailand',
      'currency': 'THB',
      'language': 'TH',
      'flag': 'TH',
    },
    {
      'countryKR': '타지키스탄',
      'countryEN': 'Tajikistan',
      'currency': 'TJS',
      'language': 'TG',
      'flag': 'TJ',
    },
    {
      'countryKR': '투르크메니스탄',
      'countryEN': 'Turkmenistan',
      'currency': 'TMT',
      'language': 'TK',
      'flag': 'TM',
    },
    {
      'countryKR': '튀니지',
      'countryEN': 'Tunisia',
      'currency': 'TND',
      'language': 'AR',
      'flag': 'TN',
    },
    {
      'countryKR': '통가',
      'countryEN': 'Tonga',
      'currency': 'TOP',
      'language': 'TO',
      'flag': 'TO',
    },
    {
      'countryKR': '튀르키예',
      'countryEN': 'Turkey',
      'currency': 'TRY',
      'language': 'TR',
      'flag': 'TR',
    },
    {
      'countryKR': '트리니다드 토바고',
      'countryEN': 'Trinidad and Tobago',
      'currency': 'TTD',
      'language': 'EN',
      'flag': 'TT',
    },
    {
      'countryKR': '대만',
      'countryEN': 'Taiwan, Province of China',
      'currency': 'TWD',
      'language': 'ZH',
      'flag': 'TW',
    },
    {
      'countryKR': '탄자니아',
      'countryEN': 'Tanzania, United Republic of',
      'currency': 'TZS',
      'language': 'SW',
      'flag': 'TZ',
    },
    {
      'countryKR': '우크라이나',
      'countryEN': 'Ukraine',
      'currency': 'UAH',
      'language': 'UK',
      'flag': 'UA',
    },
    {
      'countryKR': '우간다',
      'countryEN': 'Uganda',
      'currency': 'UGX',
      'language': 'SW',
      'flag': 'UG',
    },
    {
      'countryKR': '아메리칸 사모아',
      'countryEN': 'American Samoa',
      'currency': 'USD',
      'language': 'SM',
      'flag': 'AS',
    },
    {
      'countryKR': '네덜란드령 카리브',
      'countryEN': 'Bonaire, Sint Eustatius and Saba',
      'currency': 'USD',
      'language': 'PAP',
      'flag': 'BQ',
    },
    {
      'countryKR': '에콰도르',
      'countryEN': 'Ecuador',
      'currency': 'USD',
      'language': 'ES',
      'flag': 'EC',
    },
    {
      'countryKR': '미크로네시아',
      'countryEN': 'Micronesia, Federated States of',
      'currency': 'USD',
      'language': 'EN',
      'flag': 'FM',
    },
    {
      'countryKR': '괌',
      'countryEN': 'Guam',
      'currency': 'USD',
      'language': 'EN',
      'flag': 'GU',
    },
    {
      'countryKR': '영국령 인도양 지역',
      'countryEN': 'British Indian Ocean Territory',
      'currency': 'USD',
      'language': 'EN',
      'flag': 'IO',
    },
    {
      'countryKR': '마셜 제도',
      'countryEN': 'Marshall Islands',
      'currency': 'USD',
      'language': 'EN',
      'flag': 'MH',
    },
    {
      'countryKR': '북마리아나제도',
      'countryEN': 'Northern Mariana Islands',
      'currency': 'USD',
      'language': 'EN',
      'flag': 'MP',
    },
    {
      'countryKR': '푸에르토리코',
      'countryEN': 'Puerto Rico',
      'currency': 'USD',
      'language': 'ES',
      'flag': 'PR',
    },
    {
      'countryKR': '팔라우',
      'countryEN': 'Palau',
      'currency': 'USD',
      'language': 'PAU',
      'flag': 'PW',
    },
    {
      'countryKR': '엘살바도르',
      'countryEN': 'El Salvador',
      'currency': 'USD',
      'language': 'ES',
      'flag': 'SV',
    },
    {
      'countryKR': '터크스 케이커스 제도',
      'countryEN': 'Turks and Caicos Islands',
      'currency': 'USD',
      'language': 'EN',
      'flag': 'TC',
    },
    {
      'countryKR': '동티모르',
      'countryEN': 'Timor-Leste',
      'currency': 'USD',
      'language': 'PT',
      'flag': 'TL',
    },
    {
      'countryKR': '미국령 해외 제도',
      'countryEN': 'United States Minor Outlying Islands',
      'currency': 'USD',
      'language': 'EN',
      'flag': 'UM',
    },
    {
      'countryKR': '미국',
      'countryEN': 'United States',
      'currency': 'USD',
      'language': 'EN',
      'flag': 'US',
    },
    {
      'countryKR': '영국령 버진아일랜드',
      'countryEN': 'Virgin Islands, British',
      'currency': 'USD',
      'language': 'EN',
      'flag': 'VG',
    },
    {
      'countryKR': '미국령 버진아일랜드',
      'countryEN': 'Virgin Islands, U.S.',
      'currency': 'USD',
      'language': 'EN',
      'flag': 'VI',
    },
    {
      'countryKR': '짐바브웨',
      'countryEN': 'Zimbabwe',
      'currency': 'USD',
      'language': 'SN',
      'flag': 'ZW',
    },
    {
      'countryKR': '우루과이',
      'countryEN': 'Uruguay',
      'currency': 'UYU',
      'language': 'ES',
      'flag': 'UY',
    },
    {
      'countryKR': '우즈베키스탄',
      'countryEN': 'Uzbekistan',
      'currency': 'UZS',
      'language': 'UZ',
      'flag': 'UZ',
    },
    {
      'countryKR': '베네수엘라',
      'countryEN': 'Venezuela, Bolivarian Republic of',
      'currency': 'VES',
      'language': 'ES',
      'flag': 'VE',
    },
    {
      'countryKR': '베트남',
      'countryEN': 'Viet Nam',
      'currency': 'VND',
      'language': 'VI',
      'flag': 'VN',
    },
    {
      'countryKR': '바누아투',
      'countryEN': 'Vanuatu',
      'currency': 'VUV',
      'language': 'BI',
      'flag': 'VU',
    },
    {
      'countryKR': '사모아',
      'countryEN': 'Samoa',
      'currency': 'WST',
      'language': 'SM',
      'flag': 'WS',
    },
    {
      'countryKR': '중앙 아프리카 공화국',
      'countryEN': 'Central African Republic',
      'currency': 'XAF',
      'language': 'FR',
      'flag': 'CF',
    },
    {
      'countryKR': '콩고-브라자빌',
      'countryEN': 'Congo',
      'currency': 'XAF',
      'language': 'FR',
      'flag': 'CG',
    },
    {
      'countryKR': '카메룬',
      'countryEN': 'Cameroon',
      'currency': 'XAF',
      'language': 'FR',
      'flag': 'CM',
    },
    {
      'countryKR': '가봉',
      'countryEN': 'Gabon',
      'currency': 'XAF',
      'language': 'FR',
      'flag': 'GA',
    },
    {
      'countryKR': '적도 기니',
      'countryEN': 'Equatorial Guinea',
      'currency': 'XAF',
      'language': 'ES',
      'flag': 'GQ',
    },
    {
      'countryKR': '차드',
      'countryEN': 'Chad',
      'currency': 'XAF',
      'language': 'FR',
      'flag': 'TD',
    },
    {
      'countryKR': '앤티가 바부다',
      'countryEN': 'Antigua and Barbuda',
      'currency': 'XCD',
      'language': 'EN',
      'flag': 'AG',
    },
    {
      'countryKR': '앵귈라',
      'countryEN': 'Anguilla',
      'currency': 'XCD',
      'language': 'EN',
      'flag': 'AI',
    },
    {
      'countryKR': '도미니카',
      'countryEN': 'Dominica',
      'currency': 'XCD',
      'language': 'EN',
      'flag': 'DM',
    },
    {
      'countryKR': '그레나다',
      'countryEN': 'Grenada',
      'currency': 'XCD',
      'language': 'EN',
      'flag': 'GD',
    },
    {
      'countryKR': '세인트키츠 네비스',
      'countryEN': 'Saint Kitts and Nevis',
      'currency': 'XCD',
      'language': 'EN',
      'flag': 'KN',
    },
    {
      'countryKR': '세인트루시아',
      'countryEN': 'Saint Lucia',
      'currency': 'XCD',
      'language': 'EN',
      'flag': 'LC',
    },
    {
      'countryKR': '몬트세라트',
      'countryEN': 'Montserrat',
      'currency': 'XCD',
      'language': 'EN',
      'flag': 'MS',
    },
    {
      'countryKR': '세인트빈센트그레나딘',
      'countryEN': 'Saint Vincent and the Grenadines',
      'currency': 'XCD',
      'language': 'EN',
      'flag': 'VC',
    },
    {
      'countryKR': '퀴라소',
      'countryEN': 'Curaçao',
      'currency': 'XCG',
      'language': 'PAP',
      'flag': 'CW',
    },
    {
      'countryKR': '신트마르턴',
      'countryEN': 'Sint Maarten (Dutch part)',
      'currency': 'XCG',
      'language': 'EN',
      'flag': 'SX',
    },
    {
      'countryKR': '부르키나파소',
      'countryEN': 'Burkina Faso',
      'currency': 'XOF',
      'language': 'FR',
      'flag': 'BF',
    },
    {
      'countryKR': '베냉',
      'countryEN': 'Benin',
      'currency': 'XOF',
      'language': 'FR',
      'flag': 'BJ',
    },
    {
      'countryKR': '코트디부아르',
      'countryEN': 'Côte d\'Ivoire',
      'currency': 'XOF',
      'language': 'FR',
      'flag': 'CI',
    },
    {
      'countryKR': '기니비사우',
      'countryEN': 'Guinea-Bissau',
      'currency': 'XOF',
      'language': 'PT',
      'flag': 'GW',
    },
    {
      'countryKR': '말리',
      'countryEN': 'Mali',
      'currency': 'XOF',
      'language': 'BM',
      'flag': 'ML',
    },
    {
      'countryKR': '니제르',
      'countryEN': 'Niger',
      'currency': 'XOF',
      'language': 'HA',
      'flag': 'NE',
    },
    {
      'countryKR': '세네갈',
      'countryEN': 'Senegal',
      'currency': 'XOF',
      'language': 'FR',
      'flag': 'SN',
    },
    {
      'countryKR': '토고',
      'countryEN': 'Togo',
      'currency': 'XOF',
      'language': 'FR',
      'flag': 'TG',
    },
    {
      'countryKR': '뉴칼레도니아',
      'countryEN': 'New Caledonia',
      'currency': 'XPF',
      'language': 'FR',
      'flag': 'NC',
    },
    {
      'countryKR': '프랑스령 폴리네시아',
      'countryEN': 'French Polynesia',
      'currency': 'XPF',
      'language': 'FR',
      'flag': 'PF',
    },
    {
      'countryKR': '왈리스-푸투나 제도',
      'countryEN': 'Wallis and Futuna',
      'currency': 'XPF',
      'language': 'FR',
      'flag': 'WF',
    },
    {
      'countryKR': '예멘',
      'countryEN': 'Yemen',
      'currency': 'YER',
      'language': 'AR',
      'flag': 'YE',
    },
    {
      'countryKR': '남아프리카',
      'countryEN': 'South Africa',
      'currency': 'ZAR',
      'language': 'EN',
      'flag': 'ZA',
    },
    {
      'countryKR': '잠비아',
      'countryEN': 'Zambia',
      'currency': 'ZMW',
      'language': 'BEM',
      'flag': 'ZM',
    },
    {
      'countryKR': '짐바브웨',
      'countryEN': 'Zimbabwe',
      'currency': 'ZWG',
      'language': 'SN',
      'flag': 'ZW',
    },
  ];
}
